# Playbook is used to build and deploy an image or just to deploy an image. Functionality is dertermined by selecting roles below
#
#
#
 - hosts: all
   become: no
   # Key files should include only one variable named after the file
   # example:
   # ---
   # wildcard_discoverykidsplay_com_key: |
   #
   vars_files:
     - "users/main.yml"

   roles:
     - { role: setup_infra, tags: [ "setup_infra" ] }           
     - { role: build_and_launch_instance, tags: [ "build_and_launch_instance" ] }

   environment:
     AWS_REGION: "{{ REGION }}"
